sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/virtualenv/python2.7.9
    - node_modules
env:
  global:
    - DATABASE_URL='mysql://root@localhost/test_treeherder'
    - DATABASE_URL_RO='mysql://root@localhost/test_treeherder'
    - TREEHERDER_DJANGO_SECRET_KEY='secretkey-1234'
    - DJANGO_SETTINGS_MODULE='tests.settings'
services:
  - rabbitmq
  - memcached
install:
  - npm install
  - ./bin/peep.py install -r requirements/common.txt -r requirements/dev.txt
before_script:
  - flake8 --show-source
  - grunt checkjs
  # Required for Karma tests (http://docs.travis-ci.com/user/gui-and-headless-browsers/)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mysql -e 'create database test_treeherder;'
script:
  - npm test
  - python -m 'from django.conf import settings; dir(settings)'
  - py.test tests/$* --runslow
notifications:
  email:
    on_success: never
    on_failure: always

# Do not run these on the travis server at this time.
# The end to end tests require the service to be running, but travis can't
# start the service for us.  So we would have to have the default point to
# a dedicated dev service instance that is reach-able by travis.  However, we
# require /etc/hosts to have an entry at this point to reach our current dev
# server.  So these tests should be run only locally for now.
# - karma start config/karma-e2e.conf.js --reporters=dots --browsers=Firefox
